os:
  - windows
  - linux
  - osx
sudo: false
language: c
before_script:
    - EXE_NAME="hola"
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then EXE_NAME="hola.exe"; fi
script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
    - ./$EXE_NAME
